-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 14:54:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apps_cogip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apps_cogip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apps_cogip` DEFAULT CHARACTER SET utf8 ;
USE `apps_cogip` ;

-- -----------------------------------------------------
-- Table `apps_cogip`.`TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`TYPE` (
  `idTYPE` INT NOT NULL AUTO_INCREMENT,
  `type_entreprise` VARCHAR(45) NULL,
  PRIMARY KEY (`idTYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_cogip`.`SOCIETES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`SOCIETES` (
  `idSOCIETES` INT NOT NULL AUTO_INCREMENT,
  `nom_societe` VARCHAR(45) NULL,
  `adresse_societe` VARCHAR(45) NULL,
  `pays_societe` VARCHAR(45) NULL,
  `TVA_societe` VARCHAR(45) NULL,
  `telephone_societe` INT NULL,
  `TYPE_idTYPE` INT NOT NULL,
  PRIMARY KEY (`idSOCIETES`, `TYPE_idTYPE`),
  CONSTRAINT `fk_SOCIETES_TYPE1`
    FOREIGN KEY (`TYPE_idTYPE`)
    REFERENCES `apps_cogip`.`TYPE` (`idTYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SOCIETES_TYPE1_idx` ON `apps_cogip`.`SOCIETES` (`TYPE_idTYPE` ASC) ;


-- -----------------------------------------------------
-- Table `apps_cogip`.`PERSONNES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`PERSONNES` (
  `idPERSONNES` INT NOT NULL AUTO_INCREMENT,
  `nom_personne` VARCHAR(45) NULL,
  `prenom_presonne` VARCHAR(45) NULL,
  `telephone_personne` INT NULL,
  `email_personne` VARCHAR(45) NULL,
  `SOCIETES_idSOCIETES` INT NOT NULL,
  PRIMARY KEY (`idPERSONNES`, `SOCIETES_idSOCIETES`),
  CONSTRAINT `fk_PERSONNES_SOCIETES`
    FOREIGN KEY (`SOCIETES_idSOCIETES`)
    REFERENCES `apps_cogip`.`SOCIETES` (`idSOCIETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PERSONNES_SOCIETES_idx` ON `apps_cogip`.`PERSONNES` (`SOCIETES_idSOCIETES` ASC) ;


-- -----------------------------------------------------
-- Table `apps_cogip`.`FACTURES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`FACTURES` (
  `idFACTURES` INT NOT NULL AUTO_INCREMENT,
  `numero_facture` INT NULL,
  `date_facture` DATE NULL,
  `motif_prestation_facture` VARCHAR(45) NULL,
  `PERSONNES_idPERSONNES` INT NOT NULL,
  `PERSONNES_SOCIETES_idSOCIETES` INT NOT NULL,
  `SOCIETES_idSOCIETES1` INT NOT NULL,
  `TYPE_idTYPE` INT NOT NULL,
  PRIMARY KEY (`idFACTURES`, `PERSONNES_idPERSONNES`, `PERSONNES_SOCIETES_idSOCIETES`, `SOCIETES_idSOCIETES1`, `TYPE_idTYPE`),
  CONSTRAINT `fk_FACTURES_PERSONNES1`
    FOREIGN KEY (`PERSONNES_idPERSONNES` , `PERSONNES_SOCIETES_idSOCIETES`)
    REFERENCES `apps_cogip`.`PERSONNES` (`idPERSONNES` , `SOCIETES_idSOCIETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURES_SOCIETES1`
    FOREIGN KEY (`SOCIETES_idSOCIETES1`)
    REFERENCES `apps_cogip`.`SOCIETES` (`idSOCIETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURES_TYPE1`
    FOREIGN KEY (`TYPE_idTYPE`)
    REFERENCES `apps_cogip`.`TYPE` (`idTYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FACTURES_PERSONNES1_idx` ON `apps_cogip`.`FACTURES` (`PERSONNES_idPERSONNES` ASC, `PERSONNES_SOCIETES_idSOCIETES` ASC) ;

CREATE INDEX `fk_FACTURES_SOCIETES1_idx` ON `apps_cogip`.`FACTURES` (`SOCIETES_idSOCIETES1` ASC);

CREATE INDEX `fk_FACTURES_TYPE1_idx` ON `apps_cogip`.`FACTURES` (`TYPE_idTYPE` ASC) -- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 14:54:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apps_cogip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apps_cogip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apps_cogip` DEFAULT CHARACTER SET utf8 ;
USE `apps_cogip` ;

-- -----------------------------------------------------
-- Table `apps_cogip`.`TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`TYPE` (
  `idTYPE` INT NOT NULL AUTO_INCREMENT,
  `type_entreprise` VARCHAR(45) NULL,
  PRIMARY KEY (`idTYPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_cogip`.`SOCIETES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`SOCIETES` (
  `idSOCIETES` INT NOT NULL AUTO_INCREMENT,
  `nom_societe` VARCHAR(45) NULL,
  `adresse_societe` VARCHAR(45) NULL,
  `pays_societe` VARCHAR(45) NULL,
  `TVA_societe` VARCHAR(45) NULL,
  `telephone_societe` INT NULL,
  `TYPE_idTYPE` INT NOT NULL,
  PRIMARY KEY (`idSOCIETES`, `TYPE_idTYPE`),
  CONSTRAINT `fk_SOCIETES_TYPE1`
    FOREIGN KEY (`TYPE_idTYPE`)
    REFERENCES `apps_cogip`.`TYPE` (`idTYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SOCIETES_TYPE1_idx` ON `apps_cogip`.`SOCIETES` (`TYPE_idTYPE` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `apps_cogip`.`PERSONNES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`PERSONNES` (
  `idPERSONNES` INT NOT NULL AUTO_INCREMENT,
  `nom_personne` VARCHAR(45) NULL,
  `prenom_presonne` VARCHAR(45) NULL,
  `telephone_personne` INT NULL,
  `email_personne` VARCHAR(45) NULL,
  `SOCIETES_idSOCIETES` INT NOT NULL,
  PRIMARY KEY (`idPERSONNES`, `SOCIETES_idSOCIETES`),
  CONSTRAINT `fk_PERSONNES_SOCIETES`
    FOREIGN KEY (`SOCIETES_idSOCIETES`)
    REFERENCES `apps_cogip`.`SOCIETES` (`idSOCIETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PERSONNES_SOCIETES_idx` ON `apps_cogip`.`PERSONNES` (`SOCIETES_idSOCIETES` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `apps_cogip`.`FACTURES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_cogip`.`FACTURES` (
  `idFACTURES` INT NOT NULL AUTO_INCREMENT,
  `numero_facture` INT NULL,
  `date_facture` DATE NULL,
  `motif_prestation_facture` VARCHAR(45) NULL,
  `PERSONNES_idPERSONNES` INT NOT NULL,
  `PERSONNES_SOCIETES_idSOCIETES` INT NOT NULL,
  `SOCIETES_idSOCIETES1` INT NOT NULL,
  `TYPE_idTYPE` INT NOT NULL,
  PRIMARY KEY (`idFACTURES`, `PERSONNES_idPERSONNES`, `PERSONNES_SOCIETES_idSOCIETES`, `SOCIETES_idSOCIETES1`, `TYPE_idTYPE`),
  CONSTRAINT `fk_FACTURES_PERSONNES1`
    FOREIGN KEY (`PERSONNES_idPERSONNES` , `PERSONNES_SOCIETES_idSOCIETES`)
    REFERENCES `apps_cogip`.`PERSONNES` (`idPERSONNES` , `SOCIETES_idSOCIETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURES_SOCIETES1`
    FOREIGN KEY (`SOCIETES_idSOCIETES1`)
    REFERENCES `apps_cogip`.`SOCIETES` (`idSOCIETES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURES_TYPE1`
    FOREIGN KEY (`TYPE_idTYPE`)
    REFERENCES `apps_cogip`.`TYPE` (`idTYPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FACTURES_PERSONNES1_idx` ON `apps_cogip`.`FACTURES` (`PERSONNES_idPERSONNES` ASC, `PERSONNES_SOCIETES_idSOCIETES` ASC) VISIBLE;

CREATE INDEX `fk_FACTURES_SOCIETES1_idx` ON `apps_cogip`.`FACTURES` (`SOCIETES_idSOCIETES1` ASC) VISIBLE;

CREATE INDEX `fk_FACTURES_TYPE1_idx` ON `apps_cogip`.`FACTURES` (`TYPE_idTYPE` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
